// Generated by PEG.js v0.11.0, https://pegjs.org/

function peg$subclass(child, parent) {
  function C() { this.constructor = child; }
  C.prototype = parent.prototype;
  child.prototype = new C();
}

function peg$SyntaxError(message, expected, found, location) {
  this.message = message;
  this.expected = expected;
  this.found = found;
  this.location = location;
  this.name = "SyntaxError";

  // istanbul ignore next
  if (typeof Error.captureStackTrace === "function") {
    Error.captureStackTrace(this, peg$SyntaxError);
  }
}

peg$subclass(peg$SyntaxError, Error);

peg$SyntaxError.buildMessage = function(expected, found, location) {
  var DESCRIBE_EXPECTATION_FNS = {
    literal: function(expectation) {
      return "\"" + literalEscape(expectation.text) + "\"";
    },

    class: function(expectation) {
      var escapedParts = expectation.parts.map(function(part) {
        return Array.isArray(part)
          ? classEscape(part[0]) + "-" + classEscape(part[1])
          : classEscape(part);
      });

      return "[" + (expectation.inverted ? "^" : "") + escapedParts + "]";
    },

    any: function() {
      return "any character";
    },

    end: function() {
      return "end of input";
    },

    other: function(expectation) {
      return expectation.description;
    },

    not: function(expectation) {
      return "not " + describeExpectation(expectation.expected);
    }
  };

  function hex(ch) {
    return ch.charCodeAt(0).toString(16).toUpperCase();
  }

  function literalEscape(s) {
    return s
      .replace(/\\/g, "\\\\")
      .replace(/"/g,  "\\\"")
      .replace(/\0/g, "\\0")
      .replace(/\t/g, "\\t")
      .replace(/\n/g, "\\n")
      .replace(/\r/g, "\\r")
      .replace(/[\x00-\x0F]/g,          function(ch) { return "\\x0" + hex(ch); })
      .replace(/[\x10-\x1F\x7F-\x9F]/g, function(ch) { return "\\x"  + hex(ch); });
  }

  function classEscape(s) {
    return s
      .replace(/\\/g, "\\\\")
      .replace(/\]/g, "\\]")
      .replace(/\^/g, "\\^")
      .replace(/-/g,  "\\-")
      .replace(/\0/g, "\\0")
      .replace(/\t/g, "\\t")
      .replace(/\n/g, "\\n")
      .replace(/\r/g, "\\r")
      .replace(/[\x00-\x0F]/g,          function(ch) { return "\\x0" + hex(ch); })
      .replace(/[\x10-\x1F\x7F-\x9F]/g, function(ch) { return "\\x"  + hex(ch); });
  }

  function describeExpectation(expectation) {
    return DESCRIBE_EXPECTATION_FNS[expectation.type](expectation);
  }

  function describeExpected(expected) {
    var descriptions = expected.map(describeExpectation);
    var i, j;

    descriptions.sort();

    if (descriptions.length > 0) {
      for (i = 1, j = 1; i < descriptions.length; i++) {
        if (descriptions[i - 1] !== descriptions[i]) {
          descriptions[j] = descriptions[i];
          j++;
        }
      }
      descriptions.length = j;
    }

    switch (descriptions.length) {
      case 1:
        return descriptions[0];

      case 2:
        return descriptions[0] + " or " + descriptions[1];

      default:
        return descriptions.slice(0, -1).join(", ")
          + ", or "
          + descriptions[descriptions.length - 1];
    }
  }

  function describeFound(found) {
    return found ? "\"" + literalEscape(found) + "\"" : "end of input";
  }

  return "Expected " + describeExpected(expected) + " but " + describeFound(found) + " found.";
};

function peg$parse(input, options) {
  options = options !== undefined ? options : {};

  var peg$FAILED = {};

  var peg$startRuleFunctions = { HTMLDocument: peg$parseHTMLDocument };
  var peg$startRuleFunction = peg$parseHTMLDocument;

  var peg$c0 = "<script";
  var peg$c1 = ">";
  var peg$c2 = "</script";
  var peg$c3 = "<style";
  var peg$c4 = "</style";
  var peg$c5 = "<textarea";
  var peg$c6 = "</textarea";
  var peg$c7 = "<title";
  var peg$c8 = "</title";
  var peg$c9 = "<plaintext";
  var peg$c10 = "</plaintext";
  var peg$c11 = "<";
  var peg$c12 = "</";
  var peg$c13 = ":";
  var peg$c14 = "/>";
  var peg$c15 = "<!--";
  var peg$c16 = "-->";
  var peg$c17 = "<!doctype";
  var peg$c18 = "public";
  var peg$c19 = "system";
  var peg$c20 = "{";
  var peg$c21 = "}";
  var peg$c22 = "=";
  var peg$c23 = "\"";
  var peg$c24 = "'";

  var peg$r0 = /^[^<]/;
  var peg$r1 = /^[\\]/;
  var peg$r2 = /^[$@#]/;
  var peg$r3 = /^[^> ]/;
  var peg$r4 = /^[^"]/;
  var peg$r5 = /^[^']/;
var peg$r6 = /^[^"'<>` ]/;
  var peg$r7 = /^[a-zA-Z0-9_\-]/;
  var peg$r8 = /^[\r\n \t\f]/;
  var peg$r9 = /^[ \t\f]/;

  var peg$e0 = peg$otherExpectation("script");
  var peg$e1 = peg$otherExpectation("style");
  var peg$e2 = peg$otherExpectation("textarea");
  var peg$e3 = peg$otherExpectation("title");
  var peg$e4 = peg$otherExpectation("plaintext");
  var peg$e5 = peg$otherExpectation("element");
  var peg$e6 = peg$otherExpectation("comment");
  var peg$e7 = peg$otherExpectation("doctype");
  var peg$e8 = peg$otherExpectation("text");
  var peg$e9 = peg$otherExpectation("placeholder");
  var peg$e10 = peg$otherExpectation("space characters");

  var peg$f0 = function(nodes) { return nodes; };
  var peg$f1 = function(attrs, c) { return c };
  var peg$f2 = function(attrs, ch) { return ch.join('') };
  var peg$f3 = function(attrs, content) { return makeNode('script', attrs, content); };
  var peg$f4 = function(attrs, content) { return makeNode('style', attrs, content); };
  var peg$f5 = function(attrs, content) { return makeNode('textarea', attrs, content); };
  var peg$f6 = function(attrs, content) { return makeNode('title', attrs, content); };
  var peg$f7 = function(attrs, content) { return makeNode('plaintext', attrs, content); };
  var peg$f8 = function(begin, content, end) {
    let begin_ = begin.if ? begin.content : begin;
    if(begin_.name == end.name && ((!begin_.namespace && !end.namespace) || (begin_.namespace && (begin_.namespace == end.namespace)) )){return true} else {error('Start tag and end tag do not match.')}; 
  };
  var peg$f9 = function(begin, content, end) {
    begin.content = content;
    return begin;
  };
  var peg$f10 = function(namespace, name, attrs) { return makeNode(name.toLowerCase(), attrs,null,namespace); };
  var peg$f11 = function(namespace, name) { return {name:name.toLowerCase(),namespace:namespace}; };
  var peg$f12 = function(namespace, name, attrs) { return makeNode(name, attrs,null,namespace); };
  var peg$f13 = function(text) {
      return makeNode('comment', null, text);
    };
  var peg$f14 = function(ch) { return ch; };
  var peg$f15 = function(root, type, text) {
      const node = makeNode('doctype');
      node.root = root && root.toLowerCase();
      node.type = type && type.toLowerCase();
      //node.content = content && content.toLowerCase();
      return node;
    };
  var peg$f16 = function(ch) {
      return makeNode('text', null,ch);
    };
  var peg$f17 = function(c) { c };
  var peg$f18 = function(ch) {
      return makeNode('text', null, ch.join(''));
    };
  var peg$f19 = function(type) {return type;};
  var peg$f20 = function(type, expression) { return {name:'placeholder',type:type,expression:expression}; };
  var peg$f21 = function(attrs) { return (attrs && attrs.length) ? attrs : null;};
  var peg$f22 = function(namespace, name, value) { return {namespace:namespace,name:name, value:value?value[0]:undefined}; };
  var peg$f23 = function() { return null; };
  var peg$f24 = function(h, t) { return h + t.join('') };

  var peg$currPos = 0;
  var peg$savedPos = 0;
  var peg$posDetailsCache = [{ line: 1, column: 1 }];
  var peg$expected = [];
  var peg$silentFails = 0;

  var peg$resultsCache = {};

  var peg$result;

  if ("startRule" in options) {
    if (!(options.startRule in peg$startRuleFunctions)) {
      throw new Error("Can't start parsing from rule \"" + options.startRule + "\".");
    }

    peg$startRuleFunction = peg$startRuleFunctions[options.startRule];
  }

  function text() {
    return input.substring(peg$savedPos, peg$currPos);
  }

  function offset() {
    return peg$savedPos;
  }

  function range() {
    return [peg$savedPos, peg$currPos];
  }

  function location() {
    return peg$computeLocation(peg$savedPos, peg$currPos);
  }

  function expected(description, location) {
    location = location !== undefined
      ? location
      : peg$computeLocation(peg$savedPos, peg$currPos);

    throw peg$buildStructuredError(
      [peg$otherExpectation(description)],
      input.substring(peg$savedPos, peg$currPos),
      location
    );
  }

  function error(message, location) {
    location = location !== undefined
      ? location
      : peg$computeLocation(peg$savedPos, peg$currPos);

    throw peg$buildSimpleError(message, location);
  }

  function peg$literalExpectation(text, ignoreCase) {
    return { type: "literal", text: text, ignoreCase: ignoreCase };
  }

  function peg$classExpectation(parts, inverted, ignoreCase) {
    return { type: "class", parts: parts, inverted: inverted, ignoreCase: ignoreCase };
  }

  function peg$anyExpectation() {
    return { type: "any" };
  }

  function peg$endExpectation() {
    return { type: "end" };
  }

  function peg$otherExpectation(description) {
    return { type: "other", description: description };
  }

  function peg$computePosDetails(pos) {
    var details = peg$posDetailsCache[pos];
    var p;

    if (details) {
      return details;
    } else {
      p = pos - 1;
      while (!peg$posDetailsCache[p]) {
        p--;
      }

      details = peg$posDetailsCache[p];
      details = {
        line: details.line,
        column: details.column
      };

      while (p < pos) {
        if (input.charCodeAt(p) === 10) {
          details.line++;
          details.column = 1;
        } else {
          details.column++;
        }

        p++;
      }

      peg$posDetailsCache[pos] = details;

      return details;
    }
  }

  var peg$VALIDFILENAME = typeof options.filename === "string" && options.filename.length > 0;
  function peg$computeLocation(startPos, endPos) {
    var loc = {};

    if ( peg$VALIDFILENAME ) loc.filename = options.filename;

    var startPosDetails = peg$computePosDetails(startPos);
    loc.start = {
      offset: startPos,
      line: startPosDetails.line,
      column: startPosDetails.column
    };

    var endPosDetails = peg$computePosDetails(endPos);
    loc.end = {
      offset: endPos,
      line: endPosDetails.line,
      column: endPosDetails.column
    };

    return loc;
  }

  function peg$begin() {
    peg$expected.push({ pos: peg$currPos, variants: [] });
  }

  function peg$expect(expected) {
    var top = peg$expected[peg$expected.length - 1];

    if (peg$currPos < top.pos) { return; }

    if (peg$currPos > top.pos) {
      top.pos = peg$currPos;
      top.variants = [];
    }

    top.variants.push(expected);
  }

  function peg$end(invert) {
    var expected = peg$expected.pop();
    var top = peg$expected[peg$expected.length - 1];
    var variants = expected.variants;

    if (top.pos !== expected.pos) { return; }

    if (invert) {
      variants = variants.map(function(e) {
        return e.type === "not" ? e.expected : { type: "not", expected: e };
      });
    }

    Array.prototype.push.apply(top.variants, variants);
  }

  function peg$buildSimpleError(message, location) {
    return new peg$SyntaxError(message, null, null, location);
  }

  function peg$buildStructuredError(expected, found, location) {
    return new peg$SyntaxError(
      peg$SyntaxError.buildMessage(expected, found, location),
      expected,
      found,
      location
    );
  }

  function peg$buildError() {
    var expected = peg$expected[0];
    var failPos = expected.pos;

    return peg$buildStructuredError(
      expected.variants,
      failPos < input.length ? input.charAt(failPos) : null,
      failPos < input.length
        ? peg$computeLocation(failPos, failPos + 1)
        : peg$computeLocation(failPos, failPos)
    );
  }

  function peg$parseHTMLDocument() {
    var s0, s1, s2, s3;

    var rule$expects = function (expected) {
      if (peg$silentFails === 0) peg$expect(expected);
    }

    var key = peg$currPos * 26 + 0;
    var cached = peg$resultsCache[key];
    var rule$expectations = [];

    rule$expects = function (expected) {
      if (peg$silentFails === 0) peg$expect(expected);
      rule$expectations.push(expected);
    }

    if (cached) {
      peg$currPos = cached.nextPos;

      rule$expectations = cached.expectations;
      if (peg$silentFails === 0) {
        rule$expectations.forEach(peg$expect);
      }

      return cached.result;
    }

    s0 = peg$currPos;
    s1 = peg$parse__();
    s2 = [];
    s3 = peg$parseElement();
    while (s3 !== peg$FAILED) {
      s2.push(s3);
      s3 = peg$parseElement();
    }
    peg$savedPos = s0;
    s0 = peg$f0(s2);

    peg$resultsCache[key] = {
      nextPos: peg$currPos,
      result: s0,
      expectations: rule$expectations
    };

    return s0;
  }

  function peg$parseElement() {
    var s0;

    var rule$expects = function (expected) {
      if (peg$silentFails === 0) peg$expect(expected);
    }

    var key = peg$currPos * 26 + 1;
    var cached = peg$resultsCache[key];
    var rule$expectations = [];

    rule$expects = function (expected) {
      if (peg$silentFails === 0) peg$expect(expected);
      rule$expectations.push(expected);
    }

    if (cached) {
      peg$currPos = cached.nextPos;

      rule$expectations = cached.expectations;
      if (peg$silentFails === 0) {
        rule$expectations.forEach(peg$expect);
      }

      return cached.result;
    }

    s0 = peg$parseRawText();
    if (s0 === peg$FAILED) {
      s0 = peg$parseNested();
      if (s0 === peg$FAILED) {
        s0 = peg$parsePlaceHolder();
        if (s0 === peg$FAILED) {
          s0 = peg$parseVoid();
          if (s0 === peg$FAILED) {
            s0 = peg$parseComment();
            if (s0 === peg$FAILED) {
              s0 = peg$parseDocType();
              if (s0 === peg$FAILED) {
                s0 = peg$parseText();
              }
            }
          }
        }
      }
    }

    peg$resultsCache[key] = {
      nextPos: peg$currPos,
      result: s0,
      expectations: rule$expectations
    };

    return s0;
  }

  function peg$parseRawText() {
    var s0;

    var rule$expects = function (expected) {
      if (peg$silentFails === 0) peg$expect(expected);
    }

    var key = peg$currPos * 26 + 2;
    var cached = peg$resultsCache[key];
    var rule$expectations = [];

    rule$expects = function (expected) {
      if (peg$silentFails === 0) peg$expect(expected);
      rule$expectations.push(expected);
    }

    if (cached) {
      peg$currPos = cached.nextPos;

      rule$expectations = cached.expectations;
      if (peg$silentFails === 0) {
        rule$expectations.forEach(peg$expect);
      }

      return cached.result;
    }

    s0 = peg$parseScript();
    if (s0 === peg$FAILED) {
      s0 = peg$parseStyle();
      if (s0 === peg$FAILED) {
        s0 = peg$parseTextarea();
        if (s0 === peg$FAILED) {
          s0 = peg$parseTitle();
          if (s0 === peg$FAILED) {
            s0 = peg$parsePlainText();
          }
        }
      }
    }

    peg$resultsCache[key] = {
      nextPos: peg$currPos,
      result: s0,
      expectations: rule$expectations
    };

    return s0;
  }

  function peg$parseScript() {
    var s0, s1, s2, s3, s4, s5, s6, s7, s8, s9, s10, s11, s12;

    var rule$expects = function (expected) {
      if (peg$silentFails === 0) peg$expect(expected);
    }

    var key = peg$currPos * 26 + 3;
    var cached = peg$resultsCache[key];
    var rule$expectations = [];

    rule$expects = function (expected) {
      if (peg$silentFails === 0) peg$expect(expected);
      rule$expectations.push(expected);
    }

    if (cached) {
      peg$currPos = cached.nextPos;

      rule$expectations = cached.expectations;
      if (peg$silentFails === 0) {
        rule$expectations.forEach(peg$expect);
      }

      return cached.result;
    }

    rule$expects(peg$e0);
    peg$silentFails++;
    s0 = peg$currPos;
    if (input.substr(peg$currPos, 7).toLowerCase() === peg$c0) {
      s1 = input.substr(peg$currPos, 7);
      peg$currPos += 7;
    } else {
      s1 = peg$FAILED;
    }
    if (s1 !== peg$FAILED) {
      s2 = peg$parseAttributes();
      if (input.charCodeAt(peg$currPos) === 62) {
        s3 = peg$c1;
        peg$currPos++;
      } else {
        s3 = peg$FAILED;
      }
      if (s3 !== peg$FAILED) {
        s4 = peg$parse__();
        s5 = peg$currPos;
        s6 = [];
        s7 = peg$currPos;
        s8 = peg$currPos;
        peg$begin();
        s9 = peg$currPos;
        if (input.substr(peg$currPos, 8).toLowerCase() === peg$c2) {
          s10 = input.substr(peg$currPos, 8);
          peg$currPos += 8;
        } else {
          s10 = peg$FAILED;
        }
        if (s10 !== peg$FAILED) {
          s11 = peg$parse__();
          if (input.charCodeAt(peg$currPos) === 62) {
            s12 = peg$c1;
            peg$currPos++;
          } else {
            s12 = peg$FAILED;
          }
          if (s12 !== peg$FAILED) {
            s10 = [s10, s11, s12];
            s9 = s10;
          } else {
            peg$currPos = s9;
            s9 = peg$FAILED;
          }
        } else {
          peg$currPos = s9;
          s9 = peg$FAILED;
        }
        peg$end(true);
        if (s9 === peg$FAILED) {
          s8 = undefined;
        } else {
          peg$currPos = s8;
          s8 = peg$FAILED;
        }
        if (s8 !== peg$FAILED) {
          if (input.length > peg$currPos) {
            s9 = input.charAt(peg$currPos);
            peg$currPos++;
          } else {
            s9 = peg$FAILED;
          }
          if (s9 !== peg$FAILED) {
            peg$savedPos = s7;
            s7 = peg$f1(s2, s9);
          } else {
            peg$currPos = s7;
            s7 = peg$FAILED;
          }
        } else {
          peg$currPos = s7;
          s7 = peg$FAILED;
        }
        while (s7 !== peg$FAILED) {
          s6.push(s7);
          s7 = peg$currPos;
          s8 = peg$currPos;
          peg$begin();
          s9 = peg$currPos;
          if (input.substr(peg$currPos, 8).toLowerCase() === peg$c2) {
            s10 = input.substr(peg$currPos, 8);
            peg$currPos += 8;
          } else {
            s10 = peg$FAILED;
          }
          if (s10 !== peg$FAILED) {
            s11 = peg$parse__();
            if (input.charCodeAt(peg$currPos) === 62) {
              s12 = peg$c1;
              peg$currPos++;
            } else {
              s12 = peg$FAILED;
            }
            if (s12 !== peg$FAILED) {
              s10 = [s10, s11, s12];
              s9 = s10;
            } else {
              peg$currPos = s9;
              s9 = peg$FAILED;
            }
          } else {
            peg$currPos = s9;
            s9 = peg$FAILED;
          }
          peg$end(true);
          if (s9 === peg$FAILED) {
            s8 = undefined;
          } else {
            peg$currPos = s8;
            s8 = peg$FAILED;
          }
          if (s8 !== peg$FAILED) {
            if (input.length > peg$currPos) {
              s9 = input.charAt(peg$currPos);
              peg$currPos++;
            } else {
              s9 = peg$FAILED;
            }
            if (s9 !== peg$FAILED) {
              peg$savedPos = s7;
              s7 = peg$f1(s2, s9);
            } else {
              peg$currPos = s7;
              s7 = peg$FAILED;
            }
          } else {
            peg$currPos = s7;
            s7 = peg$FAILED;
          }
        }
        peg$savedPos = s5;
        s6 = peg$f2(s2, s6);
        s5 = s6;
        s6 = peg$parse__();
        if (input.substr(peg$currPos, 8).toLowerCase() === peg$c2) {
          s7 = input.substr(peg$currPos, 8);
          peg$currPos += 8;
        } else {
          s7 = peg$FAILED;
        }
        if (s7 !== peg$FAILED) {
          s8 = peg$parse__();
          if (input.charCodeAt(peg$currPos) === 62) {
            s9 = peg$c1;
            peg$currPos++;
          } else {
            s9 = peg$FAILED;
          }
          if (s9 !== peg$FAILED) {
            s10 = peg$parse__();
            peg$savedPos = s0;
            s0 = peg$f3(s2, s5);
          } else {
            peg$currPos = s0;
            s0 = peg$FAILED;
          }
        } else {
          peg$currPos = s0;
          s0 = peg$FAILED;
        }
      } else {
        peg$currPos = s0;
        s0 = peg$FAILED;
      }
    } else {
      peg$currPos = s0;
      s0 = peg$FAILED;
    }
    peg$silentFails--;

    peg$resultsCache[key] = {
      nextPos: peg$currPos,
      result: s0,
      expectations: rule$expectations
    };

    return s0;
  }

  function peg$parseStyle() {
    var s0, s1, s2, s3, s4, s5, s6, s7, s8, s9, s10, s11, s12;

    var rule$expects = function (expected) {
      if (peg$silentFails === 0) peg$expect(expected);
    }

    var key = peg$currPos * 26 + 4;
    var cached = peg$resultsCache[key];
    var rule$expectations = [];

    rule$expects = function (expected) {
      if (peg$silentFails === 0) peg$expect(expected);
      rule$expectations.push(expected);
    }

    if (cached) {
      peg$currPos = cached.nextPos;

      rule$expectations = cached.expectations;
      if (peg$silentFails === 0) {
        rule$expectations.forEach(peg$expect);
      }

      return cached.result;
    }

    rule$expects(peg$e1);
    peg$silentFails++;
    s0 = peg$currPos;
    if (input.substr(peg$currPos, 6).toLowerCase() === peg$c3) {
      s1 = input.substr(peg$currPos, 6);
      peg$currPos += 6;
    } else {
      s1 = peg$FAILED;
    }
    if (s1 !== peg$FAILED) {
      s2 = peg$parseAttributes();
      if (input.charCodeAt(peg$currPos) === 62) {
        s3 = peg$c1;
        peg$currPos++;
      } else {
        s3 = peg$FAILED;
      }
      if (s3 !== peg$FAILED) {
        s4 = peg$parse__();
        s5 = peg$currPos;
        s6 = [];
        s7 = peg$currPos;
        s8 = peg$currPos;
        peg$begin();
        s9 = peg$currPos;
        if (input.substr(peg$currPos, 7).toLowerCase() === peg$c4) {
          s10 = input.substr(peg$currPos, 7);
          peg$currPos += 7;
        } else {
          s10 = peg$FAILED;
        }
        if (s10 !== peg$FAILED) {
          s11 = peg$parse__();
          if (input.charCodeAt(peg$currPos) === 62) {
            s12 = peg$c1;
            peg$currPos++;
          } else {
            s12 = peg$FAILED;
          }
          if (s12 !== peg$FAILED) {
            s10 = [s10, s11, s12];
            s9 = s10;
          } else {
            peg$currPos = s9;
            s9 = peg$FAILED;
          }
        } else {
          peg$currPos = s9;
          s9 = peg$FAILED;
        }
        peg$end(true);
        if (s9 === peg$FAILED) {
          s8 = undefined;
        } else {
          peg$currPos = s8;
          s8 = peg$FAILED;
        }
        if (s8 !== peg$FAILED) {
          if (input.length > peg$currPos) {
            s9 = input.charAt(peg$currPos);
            peg$currPos++;
          } else {
            s9 = peg$FAILED;
          }
          if (s9 !== peg$FAILED) {
            peg$savedPos = s7;
            s7 = peg$f1(s2, s9);
          } else {
            peg$currPos = s7;
            s7 = peg$FAILED;
          }
        } else {
          peg$currPos = s7;
          s7 = peg$FAILED;
        }
        while (s7 !== peg$FAILED) {
          s6.push(s7);
          s7 = peg$currPos;
          s8 = peg$currPos;
          peg$begin();
          s9 = peg$currPos;
          if (input.substr(peg$currPos, 7).toLowerCase() === peg$c4) {
            s10 = input.substr(peg$currPos, 7);
            peg$currPos += 7;
          } else {
            s10 = peg$FAILED;
          }
          if (s10 !== peg$FAILED) {
            s11 = peg$parse__();
            if (input.charCodeAt(peg$currPos) === 62) {
              s12 = peg$c1;
              peg$currPos++;
            } else {
              s12 = peg$FAILED;
            }
            if (s12 !== peg$FAILED) {
              s10 = [s10, s11, s12];
              s9 = s10;
            } else {
              peg$currPos = s9;
              s9 = peg$FAILED;
            }
          } else {
            peg$currPos = s9;
            s9 = peg$FAILED;
          }
          peg$end(true);
          if (s9 === peg$FAILED) {
            s8 = undefined;
          } else {
            peg$currPos = s8;
            s8 = peg$FAILED;
          }
          if (s8 !== peg$FAILED) {
            if (input.length > peg$currPos) {
              s9 = input.charAt(peg$currPos);
              peg$currPos++;
            } else {
              s9 = peg$FAILED;
            }
            if (s9 !== peg$FAILED) {
              peg$savedPos = s7;
              s7 = peg$f1(s2, s9);
            } else {
              peg$currPos = s7;
              s7 = peg$FAILED;
            }
          } else {
            peg$currPos = s7;
            s7 = peg$FAILED;
          }
        }
        peg$savedPos = s5;
        s6 = peg$f2(s2, s6);
        s5 = s6;
        s6 = peg$parse__();
        if (input.substr(peg$currPos, 7).toLowerCase() === peg$c4) {
          s7 = input.substr(peg$currPos, 7);
          peg$currPos += 7;
        } else {
          s7 = peg$FAILED;
        }
        if (s7 !== peg$FAILED) {
          s8 = peg$parse__();
          if (input.charCodeAt(peg$currPos) === 62) {
            s9 = peg$c1;
            peg$currPos++;
          } else {
            s9 = peg$FAILED;
          }
          if (s9 !== peg$FAILED) {
            s10 = peg$parse__();
            peg$savedPos = s0;
            s0 = peg$f4(s2, s5);
          } else {
            peg$currPos = s0;
            s0 = peg$FAILED;
          }
        } else {
          peg$currPos = s0;
          s0 = peg$FAILED;
        }
      } else {
        peg$currPos = s0;
        s0 = peg$FAILED;
      }
    } else {
      peg$currPos = s0;
      s0 = peg$FAILED;
    }
    peg$silentFails--;

    peg$resultsCache[key] = {
      nextPos: peg$currPos,
      result: s0,
      expectations: rule$expectations
    };

    return s0;
  }

  function peg$parseTextarea() {
    var s0, s1, s2, s3, s4, s5, s6, s7, s8, s9, s10, s11, s12;

    var rule$expects = function (expected) {
      if (peg$silentFails === 0) peg$expect(expected);
    }

    var key = peg$currPos * 26 + 5;
    var cached = peg$resultsCache[key];
    var rule$expectations = [];

    rule$expects = function (expected) {
      if (peg$silentFails === 0) peg$expect(expected);
      rule$expectations.push(expected);
    }

    if (cached) {
      peg$currPos = cached.nextPos;

      rule$expectations = cached.expectations;
      if (peg$silentFails === 0) {
        rule$expectations.forEach(peg$expect);
      }

      return cached.result;
    }

    rule$expects(peg$e2);
    peg$silentFails++;
    s0 = peg$currPos;
    if (input.substr(peg$currPos, 9).toLowerCase() === peg$c5) {
      s1 = input.substr(peg$currPos, 9);
      peg$currPos += 9;
    } else {
      s1 = peg$FAILED;
    }
    if (s1 !== peg$FAILED) {
      s2 = peg$parseAttributes();
      if (input.charCodeAt(peg$currPos) === 62) {
        s3 = peg$c1;
        peg$currPos++;
      } else {
        s3 = peg$FAILED;
      }
      if (s3 !== peg$FAILED) {
        s4 = peg$parse__();
        s5 = peg$currPos;
        s6 = [];
        s7 = peg$currPos;
        s8 = peg$currPos;
        peg$begin();
        s9 = peg$currPos;
        if (input.substr(peg$currPos, 10).toLowerCase() === peg$c6) {
          s10 = input.substr(peg$currPos, 10);
          peg$currPos += 10;
        } else {
          s10 = peg$FAILED;
        }
        if (s10 !== peg$FAILED) {
          s11 = peg$parse__();
          if (input.charCodeAt(peg$currPos) === 62) {
            s12 = peg$c1;
            peg$currPos++;
          } else {
            s12 = peg$FAILED;
          }
          if (s12 !== peg$FAILED) {
            s10 = [s10, s11, s12];
            s9 = s10;
          } else {
            peg$currPos = s9;
            s9 = peg$FAILED;
          }
        } else {
          peg$currPos = s9;
          s9 = peg$FAILED;
        }
        peg$end(true);
        if (s9 === peg$FAILED) {
          s8 = undefined;
        } else {
          peg$currPos = s8;
          s8 = peg$FAILED;
        }
        if (s8 !== peg$FAILED) {
          if (input.length > peg$currPos) {
            s9 = input.charAt(peg$currPos);
            peg$currPos++;
          } else {
            s9 = peg$FAILED;
          }
          if (s9 !== peg$FAILED) {
            peg$savedPos = s7;
            s7 = peg$f1(s2, s9);
          } else {
            peg$currPos = s7;
            s7 = peg$FAILED;
          }
        } else {
          peg$currPos = s7;
          s7 = peg$FAILED;
        }
        while (s7 !== peg$FAILED) {
          s6.push(s7);
          s7 = peg$currPos;
          s8 = peg$currPos;
          peg$begin();
          s9 = peg$currPos;
          if (input.substr(peg$currPos, 10).toLowerCase() === peg$c6) {
            s10 = input.substr(peg$currPos, 10);
            peg$currPos += 10;
          } else {
            s10 = peg$FAILED;
          }
          if (s10 !== peg$FAILED) {
            s11 = peg$parse__();
            if (input.charCodeAt(peg$currPos) === 62) {
              s12 = peg$c1;
              peg$currPos++;
            } else {
              s12 = peg$FAILED;
            }
            if (s12 !== peg$FAILED) {
              s10 = [s10, s11, s12];
              s9 = s10;
            } else {
              peg$currPos = s9;
              s9 = peg$FAILED;
            }
          } else {
            peg$currPos = s9;
            s9 = peg$FAILED;
          }
          peg$end(true);
          if (s9 === peg$FAILED) {
            s8 = undefined;
          } else {
            peg$currPos = s8;
            s8 = peg$FAILED;
          }
          if (s8 !== peg$FAILED) {
            if (input.length > peg$currPos) {
              s9 = input.charAt(peg$currPos);
              peg$currPos++;
            } else {
              s9 = peg$FAILED;
            }
            if (s9 !== peg$FAILED) {
              peg$savedPos = s7;
              s7 = peg$f1(s2, s9);
            } else {
              peg$currPos = s7;
              s7 = peg$FAILED;
            }
          } else {
            peg$currPos = s7;
            s7 = peg$FAILED;
          }
        }
        peg$savedPos = s5;
        s6 = peg$f2(s2, s6);
        s5 = s6;
        s6 = peg$parse__();
        if (input.substr(peg$currPos, 10).toLowerCase() === peg$c6) {
          s7 = input.substr(peg$currPos, 10);
          peg$currPos += 10;
        } else {
          s7 = peg$FAILED;
        }
        if (s7 !== peg$FAILED) {
          s8 = peg$parse__();
          if (input.charCodeAt(peg$currPos) === 62) {
            s9 = peg$c1;
            peg$currPos++;
          } else {
            s9 = peg$FAILED;
          }
          if (s9 !== peg$FAILED) {
            s10 = peg$parse__();
            peg$savedPos = s0;
            s0 = peg$f5(s2, s5);
          } else {
            peg$currPos = s0;
            s0 = peg$FAILED;
          }
        } else {
          peg$currPos = s0;
          s0 = peg$FAILED;
        }
      } else {
        peg$currPos = s0;
        s0 = peg$FAILED;
      }
    } else {
      peg$currPos = s0;
      s0 = peg$FAILED;
    }
    peg$silentFails--;

    peg$resultsCache[key] = {
      nextPos: peg$currPos,
      result: s0,
      expectations: rule$expectations
    };

    return s0;
  }

  function peg$parseTitle() {
    var s0, s1, s2, s3, s4, s5, s6, s7, s8, s9, s10, s11, s12;

    var rule$expects = function (expected) {
      if (peg$silentFails === 0) peg$expect(expected);
    }

    var key = peg$currPos * 26 + 6;
    var cached = peg$resultsCache[key];
    var rule$expectations = [];

    rule$expects = function (expected) {
      if (peg$silentFails === 0) peg$expect(expected);
      rule$expectations.push(expected);
    }

    if (cached) {
      peg$currPos = cached.nextPos;

      rule$expectations = cached.expectations;
      if (peg$silentFails === 0) {
        rule$expectations.forEach(peg$expect);
      }

      return cached.result;
    }

    rule$expects(peg$e3);
    peg$silentFails++;
    s0 = peg$currPos;
    if (input.substr(peg$currPos, 6).toLowerCase() === peg$c7) {
      s1 = input.substr(peg$currPos, 6);
      peg$currPos += 6;
    } else {
      s1 = peg$FAILED;
    }
    if (s1 !== peg$FAILED) {
      s2 = peg$parseAttributes();
      if (input.charCodeAt(peg$currPos) === 62) {
        s3 = peg$c1;
        peg$currPos++;
      } else {
        s3 = peg$FAILED;
      }
      if (s3 !== peg$FAILED) {
        s4 = peg$parse__();
        s5 = peg$currPos;
        s6 = [];
        s7 = peg$currPos;
        s8 = peg$currPos;
        peg$begin();
        s9 = peg$currPos;
        if (input.substr(peg$currPos, 7).toLowerCase() === peg$c8) {
          s10 = input.substr(peg$currPos, 7);
          peg$currPos += 7;
        } else {
          s10 = peg$FAILED;
        }
        if (s10 !== peg$FAILED) {
          s11 = peg$parse__();
          if (input.charCodeAt(peg$currPos) === 62) {
            s12 = peg$c1;
            peg$currPos++;
          } else {
            s12 = peg$FAILED;
          }
          if (s12 !== peg$FAILED) {
            s10 = [s10, s11, s12];
            s9 = s10;
          } else {
            peg$currPos = s9;
            s9 = peg$FAILED;
          }
        } else {
          peg$currPos = s9;
          s9 = peg$FAILED;
        }
        peg$end(true);
        if (s9 === peg$FAILED) {
          s8 = undefined;
        } else {
          peg$currPos = s8;
          s8 = peg$FAILED;
        }
        if (s8 !== peg$FAILED) {
          if (input.length > peg$currPos) {
            s9 = input.charAt(peg$currPos);
            peg$currPos++;
          } else {
            s9 = peg$FAILED;
          }
          if (s9 !== peg$FAILED) {
            peg$savedPos = s7;
            s7 = peg$f1(s2, s9);
          } else {
            peg$currPos = s7;
            s7 = peg$FAILED;
          }
        } else {
          peg$currPos = s7;
          s7 = peg$FAILED;
        }
        while (s7 !== peg$FAILED) {
          s6.push(s7);
          s7 = peg$currPos;
          s8 = peg$currPos;
          peg$begin();
          s9 = peg$currPos;
          if (input.substr(peg$currPos, 7).toLowerCase() === peg$c8) {
            s10 = input.substr(peg$currPos, 7);
            peg$currPos += 7;
          } else {
            s10 = peg$FAILED;
          }
          if (s10 !== peg$FAILED) {
            s11 = peg$parse__();
            if (input.charCodeAt(peg$currPos) === 62) {
              s12 = peg$c1;
              peg$currPos++;
            } else {
              s12 = peg$FAILED;
            }
            if (s12 !== peg$FAILED) {
              s10 = [s10, s11, s12];
              s9 = s10;
            } else {
              peg$currPos = s9;
              s9 = peg$FAILED;
            }
          } else {
            peg$currPos = s9;
            s9 = peg$FAILED;
          }
          peg$end(true);
          if (s9 === peg$FAILED) {
            s8 = undefined;
          } else {
            peg$currPos = s8;
            s8 = peg$FAILED;
          }
          if (s8 !== peg$FAILED) {
            if (input.length > peg$currPos) {
              s9 = input.charAt(peg$currPos);
              peg$currPos++;
            } else {
              s9 = peg$FAILED;
            }
            if (s9 !== peg$FAILED) {
              peg$savedPos = s7;
              s7 = peg$f1(s2, s9);
            } else {
              peg$currPos = s7;
              s7 = peg$FAILED;
            }
          } else {
            peg$currPos = s7;
            s7 = peg$FAILED;
          }
        }
        peg$savedPos = s5;
        s6 = peg$f2(s2, s6);
        s5 = s6;
        s6 = peg$parse__();
        if (input.substr(peg$currPos, 7).toLowerCase() === peg$c8) {
          s7 = input.substr(peg$currPos, 7);
          peg$currPos += 7;
        } else {
          s7 = peg$FAILED;
        }
        if (s7 !== peg$FAILED) {
          s8 = peg$parse__();
          if (input.charCodeAt(peg$currPos) === 62) {
            s9 = peg$c1;
            peg$currPos++;
          } else {
            s9 = peg$FAILED;
          }
          if (s9 !== peg$FAILED) {
            s10 = peg$parse__();
            peg$savedPos = s0;
            s0 = peg$f6(s2, s5);
          } else {
            peg$currPos = s0;
            s0 = peg$FAILED;
          }
        } else {
          peg$currPos = s0;
          s0 = peg$FAILED;
        }
      } else {
        peg$currPos = s0;
        s0 = peg$FAILED;
      }
    } else {
      peg$currPos = s0;
      s0 = peg$FAILED;
    }
    peg$silentFails--;

    peg$resultsCache[key] = {
      nextPos: peg$currPos,
      result: s0,
      expectations: rule$expectations
    };

    return s0;
  }

  function peg$parsePlainText() {
    var s0, s1, s2, s3, s4, s5, s6, s7, s8, s9, s10, s11, s12;

    var rule$expects = function (expected) {
      if (peg$silentFails === 0) peg$expect(expected);
    }

    var key = peg$currPos * 26 + 7;
    var cached = peg$resultsCache[key];
    var rule$expectations = [];

    rule$expects = function (expected) {
      if (peg$silentFails === 0) peg$expect(expected);
      rule$expectations.push(expected);
    }

    if (cached) {
      peg$currPos = cached.nextPos;

      rule$expectations = cached.expectations;
      if (peg$silentFails === 0) {
        rule$expectations.forEach(peg$expect);
      }

      return cached.result;
    }

    rule$expects(peg$e4);
    peg$silentFails++;
    s0 = peg$currPos;
    if (input.substr(peg$currPos, 10).toLowerCase() === peg$c9) {
      s1 = input.substr(peg$currPos, 10);
      peg$currPos += 10;
    } else {
      s1 = peg$FAILED;
    }
    if (s1 !== peg$FAILED) {
      s2 = peg$parseAttributes();
      if (input.charCodeAt(peg$currPos) === 62) {
        s3 = peg$c1;
        peg$currPos++;
      } else {
        s3 = peg$FAILED;
      }
      if (s3 !== peg$FAILED) {
        s4 = peg$parse__();
        s5 = peg$currPos;
        s6 = [];
        s7 = peg$currPos;
        s8 = peg$currPos;
        peg$begin();
        s9 = peg$currPos;
        if (input.substr(peg$currPos, 11).toLowerCase() === peg$c10) {
          s10 = input.substr(peg$currPos, 11);
          peg$currPos += 11;
        } else {
          s10 = peg$FAILED;
        }
        if (s10 !== peg$FAILED) {
          s11 = peg$parse__();
          if (input.charCodeAt(peg$currPos) === 62) {
            s12 = peg$c1;
            peg$currPos++;
          } else {
            s12 = peg$FAILED;
          }
          if (s12 !== peg$FAILED) {
            s10 = [s10, s11, s12];
            s9 = s10;
          } else {
            peg$currPos = s9;
            s9 = peg$FAILED;
          }
        } else {
          peg$currPos = s9;
          s9 = peg$FAILED;
        }
        peg$end(true);
        if (s9 === peg$FAILED) {
          s8 = undefined;
        } else {
          peg$currPos = s8;
          s8 = peg$FAILED;
        }
        if (s8 !== peg$FAILED) {
          if (input.length > peg$currPos) {
            s9 = input.charAt(peg$currPos);
            peg$currPos++;
          } else {
            s9 = peg$FAILED;
          }
          if (s9 !== peg$FAILED) {
            peg$savedPos = s7;
            s7 = peg$f1(s2, s9);
          } else {
            peg$currPos = s7;
            s7 = peg$FAILED;
          }
        } else {
          peg$currPos = s7;
          s7 = peg$FAILED;
        }
        while (s7 !== peg$FAILED) {
          s6.push(s7);
          s7 = peg$currPos;
          s8 = peg$currPos;
          peg$begin();
          s9 = peg$currPos;
          if (input.substr(peg$currPos, 11).toLowerCase() === peg$c10) {
            s10 = input.substr(peg$currPos, 11);
            peg$currPos += 11;
          } else {
            s10 = peg$FAILED;
          }
          if (s10 !== peg$FAILED) {
            s11 = peg$parse__();
            if (input.charCodeAt(peg$currPos) === 62) {
              s12 = peg$c1;
              peg$currPos++;
            } else {
              s12 = peg$FAILED;
            }
            if (s12 !== peg$FAILED) {
              s10 = [s10, s11, s12];
              s9 = s10;
            } else {
              peg$currPos = s9;
              s9 = peg$FAILED;
            }
          } else {
            peg$currPos = s9;
            s9 = peg$FAILED;
          }
          peg$end(true);
          if (s9 === peg$FAILED) {
            s8 = undefined;
          } else {
            peg$currPos = s8;
            s8 = peg$FAILED;
          }
          if (s8 !== peg$FAILED) {
            if (input.length > peg$currPos) {
              s9 = input.charAt(peg$currPos);
              peg$currPos++;
            } else {
              s9 = peg$FAILED;
            }
            if (s9 !== peg$FAILED) {
              peg$savedPos = s7;
              s7 = peg$f1(s2, s9);
            } else {
              peg$currPos = s7;
              s7 = peg$FAILED;
            }
          } else {
            peg$currPos = s7;
            s7 = peg$FAILED;
          }
        }
        peg$savedPos = s5;
        s6 = peg$f2(s2, s6);
        s5 = s6;
        s6 = peg$parse__();
        if (input.substr(peg$currPos, 11).toLowerCase() === peg$c10) {
          s7 = input.substr(peg$currPos, 11);
          peg$currPos += 11;
        } else {
          s7 = peg$FAILED;
        }
        if (s7 !== peg$FAILED) {
          s8 = peg$parse__();
          if (input.charCodeAt(peg$currPos) === 62) {
            s9 = peg$c1;
            peg$currPos++;
          } else {
            s9 = peg$FAILED;
          }
          if (s9 !== peg$FAILED) {
            s10 = peg$parse__();
            peg$savedPos = s0;
            s0 = peg$f7(s2, s5);
          } else {
            peg$currPos = s0;
            s0 = peg$FAILED;
          }
        } else {
          peg$currPos = s0;
          s0 = peg$FAILED;
        }
      } else {
        peg$currPos = s0;
        s0 = peg$FAILED;
      }
    } else {
      peg$currPos = s0;
      s0 = peg$FAILED;
    }
    peg$silentFails--;

    peg$resultsCache[key] = {
      nextPos: peg$currPos,
      result: s0,
      expectations: rule$expectations
    };

    return s0;
  }

  function peg$parseNested() {
    var s0, s1, s2, s3, s4, s5, s6, s7;

    var rule$expects = function (expected) {
      if (peg$silentFails === 0) peg$expect(expected);
    }

    var key = peg$currPos * 26 + 8;
    var cached = peg$resultsCache[key];
    var rule$expectations = [];

    rule$expects = function (expected) {
      if (peg$silentFails === 0) peg$expect(expected);
      rule$expectations.push(expected);
    }

    if (cached) {
      peg$currPos = cached.nextPos;

      rule$expectations = cached.expectations;
      if (peg$silentFails === 0) {
        rule$expectations.forEach(peg$expect);
      }

      return cached.result;
    }

    rule$expects(peg$e5);
    peg$silentFails++;
    s0 = peg$currPos;
    s1 = peg$parseTagBegin();
    if (s1 !== peg$FAILED) {
      s2 = peg$parse__();
      s3 = [];
      s4 = peg$parseElement();
      while (s4 !== peg$FAILED) {
        s3.push(s4);
        s4 = peg$parseElement();
      }
      s4 = peg$parse__();
      s5 = peg$parseTagEnd();
      if (s5 !== peg$FAILED) {
        s6 = peg$parse__();
        peg$savedPos = peg$currPos;
        s7 = peg$f8(s1, s3, s5);
        if (s7) {
          s7 = undefined;
        } else {
          s7 = peg$FAILED;
        }
        if (s7 !== peg$FAILED) {
          peg$savedPos = s0;
          s0 = peg$f9(s1, s3, s5);
        } else {
          peg$currPos = s0;
          s0 = peg$FAILED;
        }
      } else {
        peg$currPos = s0;
        s0 = peg$FAILED;
      }
    } else {
      peg$currPos = s0;
      s0 = peg$FAILED;
    }
    peg$silentFails--;

    peg$resultsCache[key] = {
      nextPos: peg$currPos,
      result: s0,
      expectations: rule$expectations
    };

    return s0;
  }

  function peg$parseTagBegin() {
    var s0, s1, s2, s3, s4, s5;

    var rule$expects = function (expected) {
      if (peg$silentFails === 0) peg$expect(expected);
    }

    var key = peg$currPos * 26 + 9;
    var cached = peg$resultsCache[key];
    var rule$expectations = [];

    rule$expects = function (expected) {
      if (peg$silentFails === 0) peg$expect(expected);
      rule$expectations.push(expected);
    }

    if (cached) {
      peg$currPos = cached.nextPos;

      rule$expectations = cached.expectations;
      if (peg$silentFails === 0) {
        rule$expectations.forEach(peg$expect);
      }

      return cached.result;
    }

    s0 = peg$currPos;
    if (input.charCodeAt(peg$currPos) === 60) {
      s1 = peg$c11;
      peg$currPos++;
    } else {
      s1 = peg$FAILED;
    }
    if (s1 !== peg$FAILED) {
      s2 = peg$parseNameSpace();
      if (s2 === peg$FAILED) {
        s2 = null;
      }
      s3 = peg$parseSymbol();
      if (s3 !== peg$FAILED) {
        s4 = peg$parseAttributes();
        if (input.charCodeAt(peg$currPos) === 62) {
          s5 = peg$c1;
          peg$currPos++;
        } else {
          s5 = peg$FAILED;
        }
        if (s5 !== peg$FAILED) {
          peg$savedPos = s0;
          s0 = peg$f10(s2, s3, s4);
        } else {
          peg$currPos = s0;
          s0 = peg$FAILED;
        }
      } else {
        peg$currPos = s0;
        s0 = peg$FAILED;
      }
    } else {
      peg$currPos = s0;
      s0 = peg$FAILED;
    }

    peg$resultsCache[key] = {
      nextPos: peg$currPos,
      result: s0,
      expectations: rule$expectations
    };

    return s0;
  }

  function peg$parseTagEnd() {
    var s0, s1, s2, s3, s4, s5;

    var rule$expects = function (expected) {
      if (peg$silentFails === 0) peg$expect(expected);
    }

    var key = peg$currPos * 26 + 10;
    var cached = peg$resultsCache[key];
    var rule$expectations = [];

    rule$expects = function (expected) {
      if (peg$silentFails === 0) peg$expect(expected);
      rule$expectations.push(expected);
    }

    if (cached) {
      peg$currPos = cached.nextPos;

      rule$expectations = cached.expectations;
      if (peg$silentFails === 0) {
        rule$expectations.forEach(peg$expect);
      }

      return cached.result;
    }

    s0 = peg$currPos;
    if (input.substr(peg$currPos, 2) === peg$c12) {
      s1 = peg$c12;
      peg$currPos += 2;
    } else {
      s1 = peg$FAILED;
    }
    if (s1 !== peg$FAILED) {
      s2 = peg$parseNameSpace();
      if (s2 === peg$FAILED) {
        s2 = null;
      }
      s3 = peg$parseSymbol();
      if (s3 !== peg$FAILED) {
        s4 = peg$parse__();
        if (input.charCodeAt(peg$currPos) === 62) {
          s5 = peg$c1;
          peg$currPos++;
        } else {
          s5 = peg$FAILED;
        }
        if (s5 !== peg$FAILED) {
          peg$savedPos = s0;
          s0 = peg$f11(s2, s3);
        } else {
          peg$currPos = s0;
          s0 = peg$FAILED;
        }
      } else {
        peg$currPos = s0;
        s0 = peg$FAILED;
      }
    } else {
      peg$currPos = s0;
      s0 = peg$FAILED;
    }

    peg$resultsCache[key] = {
      nextPos: peg$currPos,
      result: s0,
      expectations: rule$expectations
    };

    return s0;
  }

  function peg$parseNameSpace() {
    var s0, s1, s2;

    var rule$expects = function (expected) {
      if (peg$silentFails === 0) peg$expect(expected);
    }

    var key = peg$currPos * 26 + 11;
    var cached = peg$resultsCache[key];
    var rule$expectations = [];

    rule$expects = function (expected) {
      if (peg$silentFails === 0) peg$expect(expected);
      rule$expectations.push(expected);
    }

    if (cached) {
      peg$currPos = cached.nextPos;

      rule$expectations = cached.expectations;
      if (peg$silentFails === 0) {
        rule$expectations.forEach(peg$expect);
      }

      return cached.result;
    }

    s0 = peg$currPos;
    s1 = peg$parseSymbol();
    if (s1 !== peg$FAILED) {
      if (input.charCodeAt(peg$currPos) === 58) {
        s2 = peg$c13;
        peg$currPos++;
      } else {
        s2 = peg$FAILED;
      }
      if (s2 !== peg$FAILED) {
        s0 = s1;
      } else {
        peg$currPos = s0;
        s0 = peg$FAILED;
      }
    } else {
      peg$currPos = s0;
      s0 = peg$FAILED;
    }

    peg$resultsCache[key] = {
      nextPos: peg$currPos,
      result: s0,
      expectations: rule$expectations
    };

    return s0;
  }

  function peg$parseVoid() {
    var s0, s1, s2, s3, s4, s5, s6;

    var rule$expects = function (expected) {
      if (peg$silentFails === 0) peg$expect(expected);
    }

    var key = peg$currPos * 26 + 12;
    var cached = peg$resultsCache[key];
    var rule$expectations = [];

    rule$expects = function (expected) {
      if (peg$silentFails === 0) peg$expect(expected);
      rule$expectations.push(expected);
    }

    if (cached) {
      peg$currPos = cached.nextPos;

      rule$expectations = cached.expectations;
      if (peg$silentFails === 0) {
        rule$expectations.forEach(peg$expect);
      }

      return cached.result;
    }

    rule$expects(peg$e5);
    peg$silentFails++;
    s0 = peg$currPos;
    if (input.charCodeAt(peg$currPos) === 60) {
      s1 = peg$c11;
      peg$currPos++;
    } else {
      s1 = peg$FAILED;
    }
    if (s1 !== peg$FAILED) {
      s2 = peg$parseNameSpace();
      if (s2 === peg$FAILED) {
        s2 = null;
      }
      s3 = peg$parseSymbol();
      if (s3 !== peg$FAILED) {
        s4 = peg$parseAttributes();
        if (input.substr(peg$currPos, 2) === peg$c14) {
          s5 = peg$c14;
          peg$currPos += 2;
        } else {
          s5 = peg$FAILED;
        }
        if (s5 === peg$FAILED) {
          if (input.charCodeAt(peg$currPos) === 62) {
            s5 = peg$c1;
            peg$currPos++;
          } else {
            s5 = peg$FAILED;
          }
        }
        if (s5 !== peg$FAILED) {
          s6 = peg$parse__();
          peg$savedPos = s0;
          s0 = peg$f12(s2, s3, s4);
        } else {
          peg$currPos = s0;
          s0 = peg$FAILED;
        }
      } else {
        peg$currPos = s0;
        s0 = peg$FAILED;
      }
    } else {
      peg$currPos = s0;
      s0 = peg$FAILED;
    }
    peg$silentFails--;

    peg$resultsCache[key] = {
      nextPos: peg$currPos,
      result: s0,
      expectations: rule$expectations
    };

    return s0;
  }

  function peg$parseComment() {
    var s0, s1, s2, s3, s4;

    var rule$expects = function (expected) {
      if (peg$silentFails === 0) peg$expect(expected);
    }

    var key = peg$currPos * 26 + 13;
    var cached = peg$resultsCache[key];
    var rule$expectations = [];

    rule$expects = function (expected) {
      if (peg$silentFails === 0) peg$expect(expected);
      rule$expectations.push(expected);
    }

    if (cached) {
      peg$currPos = cached.nextPos;

      rule$expectations = cached.expectations;
      if (peg$silentFails === 0) {
        rule$expectations.forEach(peg$expect);
      }

      return cached.result;
    }

    rule$expects(peg$e6);
    peg$silentFails++;
    s0 = peg$currPos;
    if (input.substr(peg$currPos, 4) === peg$c15) {
      s1 = peg$c15;
      peg$currPos += 4;
    } else {
      s1 = peg$FAILED;
    }
    if (s1 !== peg$FAILED) {
      s2 = peg$parseCommentText();
      if (input.substr(peg$currPos, 3) === peg$c16) {
        s3 = peg$c16;
        peg$currPos += 3;
      } else {
        s3 = peg$FAILED;
      }
      if (s3 !== peg$FAILED) {
        s4 = peg$parse__();
        peg$savedPos = s0;
        s0 = peg$f13(s2);
      } else {
        peg$currPos = s0;
        s0 = peg$FAILED;
      }
    } else {
      peg$currPos = s0;
      s0 = peg$FAILED;
    }
    peg$silentFails--;

    peg$resultsCache[key] = {
      nextPos: peg$currPos,
      result: s0,
      expectations: rule$expectations
    };

    return s0;
  }

  function peg$parseCommentText() {
    var s0, s1, s2, s3, s4, s5;

    var rule$expects = function (expected) {
      if (peg$silentFails === 0) peg$expect(expected);
    }

    var key = peg$currPos * 26 + 14;
    var cached = peg$resultsCache[key];
    var rule$expectations = [];

    rule$expects = function (expected) {
      if (peg$silentFails === 0) peg$expect(expected);
      rule$expectations.push(expected);
    }

    if (cached) {
      peg$currPos = cached.nextPos;

      rule$expectations = cached.expectations;
      if (peg$silentFails === 0) {
        rule$expectations.forEach(peg$expect);
      }

      return cached.result;
    }

    s0 = peg$currPos;
    s1 = peg$currPos;
    s2 = [];
    s3 = peg$currPos;
    s4 = peg$currPos;
    peg$begin();
    if (input.substr(peg$currPos, 3) === peg$c16) {
      s5 = peg$c16;
      peg$currPos += 3;
    } else {
      s5 = peg$FAILED;
    }
    peg$end(true);
    if (s5 === peg$FAILED) {
      s4 = undefined;
    } else {
      peg$currPos = s4;
      s4 = peg$FAILED;
    }
    if (s4 !== peg$FAILED) {
      if (input.length > peg$currPos) {
        s5 = input.charAt(peg$currPos);
        peg$currPos++;
      } else {
        s5 = peg$FAILED;
      }
      if (s5 !== peg$FAILED) {
        s4 = [s4, s5];
        s3 = s4;
      } else {
        peg$currPos = s3;
        s3 = peg$FAILED;
      }
    } else {
      peg$currPos = s3;
      s3 = peg$FAILED;
    }
    while (s3 !== peg$FAILED) {
      s2.push(s3);
      s3 = peg$currPos;
      s4 = peg$currPos;
      peg$begin();
      if (input.substr(peg$currPos, 3) === peg$c16) {
        s5 = peg$c16;
        peg$currPos += 3;
      } else {
        s5 = peg$FAILED;
      }
      peg$end(true);
      if (s5 === peg$FAILED) {
        s4 = undefined;
      } else {
        peg$currPos = s4;
        s4 = peg$FAILED;
      }
      if (s4 !== peg$FAILED) {
        if (input.length > peg$currPos) {
          s5 = input.charAt(peg$currPos);
          peg$currPos++;
        } else {
          s5 = peg$FAILED;
        }
        if (s5 !== peg$FAILED) {
          s4 = [s4, s5];
          s3 = s4;
        } else {
          peg$currPos = s3;
          s3 = peg$FAILED;
        }
      } else {
        peg$currPos = s3;
        s3 = peg$FAILED;
      }
    }
    s1 = input.substring(s1, peg$currPos);
    peg$savedPos = s0;
    s1 = peg$f14(s1);
    s0 = s1;

    peg$resultsCache[key] = {
      nextPos: peg$currPos,
      result: s0,
      expectations: rule$expectations
    };

    return s0;
  }

  function peg$parseDocType() {
    var s0, s1, s2, s3, s4, s5, s6, s7, s8, s9;

    var rule$expects = function (expected) {
      if (peg$silentFails === 0) peg$expect(expected);
    }

    var key = peg$currPos * 26 + 15;
    var cached = peg$resultsCache[key];
    var rule$expectations = [];

    rule$expects = function (expected) {
      if (peg$silentFails === 0) peg$expect(expected);
      rule$expectations.push(expected);
    }

    if (cached) {
      peg$currPos = cached.nextPos;

      rule$expectations = cached.expectations;
      if (peg$silentFails === 0) {
        rule$expectations.forEach(peg$expect);
      }

      return cached.result;
    }

    rule$expects(peg$e7);
    peg$silentFails++;
    s0 = peg$currPos;
    if (input.substr(peg$currPos, 9).toLowerCase() === peg$c17) {
      s1 = input.substr(peg$currPos, 9);
      peg$currPos += 9;
    } else {
      s1 = peg$FAILED;
    }
    if (s1 !== peg$FAILED) {
      s2 = peg$parse__();
      s3 = peg$parseSymbol();
      if (s3 !== peg$FAILED) {
        s4 = peg$parse__();
        if (input.substr(peg$currPos, 6).toLowerCase() === peg$c18) {
          s5 = input.substr(peg$currPos, 6);
          peg$currPos += 6;
        } else {
          s5 = peg$FAILED;
        }
        if (s5 === peg$FAILED) {
          if (input.substr(peg$currPos, 6).toLowerCase() === peg$c19) {
            s5 = input.substr(peg$currPos, 6);
            peg$currPos += 6;
          } else {
            s5 = peg$FAILED;
          }
        }
        if (s5 === peg$FAILED) {
          s5 = null;
        }
        s6 = peg$parse__();
        s7 = [];
        s8 = peg$parseString();
        while (s8 !== peg$FAILED) {
          s7.push(s8);
          s8 = peg$parseString();
        }
        if (input.charCodeAt(peg$currPos) === 62) {
          s8 = peg$c1;
          peg$currPos++;
        } else {
          s8 = peg$FAILED;
        }
        if (s8 !== peg$FAILED) {
          s9 = peg$parse__();
          peg$savedPos = s0;
          s0 = peg$f15(s3, s5, s7);
        } else {
          peg$currPos = s0;
          s0 = peg$FAILED;
        }
      } else {
        peg$currPos = s0;
        s0 = peg$FAILED;
      }
    } else {
      peg$currPos = s0;
      s0 = peg$FAILED;
    }
    peg$silentFails--;

    peg$resultsCache[key] = {
      nextPos: peg$currPos,
      result: s0,
      expectations: rule$expectations
    };

    return s0;
  }

  function peg$parseText() {
    var s0, s1, s2, s3, s4, s5, s6, s7, s8;

    var rule$expects = function (expected) {
      if (peg$silentFails === 0) peg$expect(expected);
    }

    var key = peg$currPos * 26 + 16;
    var cached = peg$resultsCache[key];
    var rule$expectations = [];

    rule$expects = function (expected) {
      if (peg$silentFails === 0) peg$expect(expected);
      rule$expectations.push(expected);
    }

    if (cached) {
      peg$currPos = cached.nextPos;

      rule$expectations = cached.expectations;
      if (peg$silentFails === 0) {
        rule$expectations.forEach(peg$expect);
      }

      return cached.result;
    }

    rule$expects(peg$e8);
    peg$silentFails++;
    s0 = peg$currPos;
    s1 = peg$currPos;
    s2 = [];
    s3 = peg$currPos;
    s4 = peg$currPos;
    peg$begin();
    s5 = peg$parsePlaceHolder();
    peg$end(true);
    if (s5 === peg$FAILED) {
      s4 = undefined;
    } else {
      peg$currPos = s4;
      s4 = peg$FAILED;
    }
    if (s4 !== peg$FAILED) {
      if (peg$r0.test(input.charAt(peg$currPos))) {
        s5 = input.charAt(peg$currPos);
        peg$currPos++;
      } else {
        s5 = peg$FAILED;
      }
      if (s5 !== peg$FAILED) {
        s4 = [s4, s5];
        s3 = s4;
      } else {
        peg$currPos = s3;
        s3 = peg$FAILED;
      }
    } else {
      peg$currPos = s3;
      s3 = peg$FAILED;
    }
    if (s3 !== peg$FAILED) {
      while (s3 !== peg$FAILED) {
        s2.push(s3);
        s3 = peg$currPos;
        s4 = peg$currPos;
        peg$begin();
        s5 = peg$parsePlaceHolder();
        peg$end(true);
        if (s5 === peg$FAILED) {
          s4 = undefined;
        } else {
          peg$currPos = s4;
          s4 = peg$FAILED;
        }
        if (s4 !== peg$FAILED) {
          if (peg$r0.test(input.charAt(peg$currPos))) {
            s5 = input.charAt(peg$currPos);
            peg$currPos++;
          } else {
            s5 = peg$FAILED;
          }
          if (s5 !== peg$FAILED) {
            s4 = [s4, s5];
            s3 = s4;
          } else {
            peg$currPos = s3;
            s3 = peg$FAILED;
          }
        } else {
          peg$currPos = s3;
          s3 = peg$FAILED;
        }
      }
    } else {
      s2 = peg$FAILED;
    }
    if (s2 !== peg$FAILED) {
      s1 = input.substring(s1, peg$currPos);
    } else {
      s1 = s2;
    }
    if (s1 !== peg$FAILED) {
      peg$savedPos = s0;
      s1 = peg$f16(s1);
    }
    s0 = s1;
    if (s0 === peg$FAILED) {
      s0 = peg$currPos;
      s1 = [];
      s2 = peg$currPos;
      s3 = peg$currPos;
      peg$begin();
      s4 = peg$parsePlaceHolder();
      peg$end(true);
      if (s4 === peg$FAILED) {
        s3 = undefined;
      } else {
        peg$currPos = s3;
        s3 = peg$FAILED;
      }
      if (s3 !== peg$FAILED) {
        s4 = peg$currPos;
        peg$begin();
        s5 = peg$parseTagEnd();
        peg$end(true);
        if (s5 === peg$FAILED) {
          s4 = undefined;
        } else {
          peg$currPos = s4;
          s4 = peg$FAILED;
        }
        if (s4 !== peg$FAILED) {
          s5 = peg$currPos;
          peg$begin();
          s6 = peg$parseVoid();
          peg$end(true);
          if (s6 === peg$FAILED) {
            s5 = undefined;
          } else {
            peg$currPos = s5;
            s5 = peg$FAILED;
          }
          if (s5 !== peg$FAILED) {
            s6 = peg$currPos;
            peg$begin();
            s7 = peg$parseComment();
            peg$end(true);
            if (s7 === peg$FAILED) {
              s6 = undefined;
            } else {
              peg$currPos = s6;
              s6 = peg$FAILED;
            }
            if (s6 !== peg$FAILED) {
              s7 = peg$currPos;
              peg$begin();
              s8 = peg$parseDocType();
              peg$end(true);
              if (s8 === peg$FAILED) {
                s7 = undefined;
              } else {
                peg$currPos = s7;
                s7 = peg$FAILED;
              }
              if (s7 !== peg$FAILED) {
                if (input.length > peg$currPos) {
                  s8 = input.charAt(peg$currPos);
                  peg$currPos++;
                } else {
                  s8 = peg$FAILED;
                }
                if (s8 !== peg$FAILED) {
                  peg$savedPos = s2;
                  s2 = peg$f17(s8);
                } else {
                  peg$currPos = s2;
                  s2 = peg$FAILED;
                }
              } else {
                peg$currPos = s2;
                s2 = peg$FAILED;
              }
            } else {
              peg$currPos = s2;
              s2 = peg$FAILED;
            }
          } else {
            peg$currPos = s2;
            s2 = peg$FAILED;
          }
        } else {
          peg$currPos = s2;
          s2 = peg$FAILED;
        }
      } else {
        peg$currPos = s2;
        s2 = peg$FAILED;
      }
      if (s2 !== peg$FAILED) {
        while (s2 !== peg$FAILED) {
          s1.push(s2);
          s2 = peg$currPos;
          s3 = peg$currPos;
          peg$begin();
          s4 = peg$parsePlaceHolder();
          peg$end(true);
          if (s4 === peg$FAILED) {
            s3 = undefined;
          } else {
            peg$currPos = s3;
            s3 = peg$FAILED;
          }
          if (s3 !== peg$FAILED) {
            s4 = peg$currPos;
            peg$begin();
            s5 = peg$parseTagEnd();
            peg$end(true);
            if (s5 === peg$FAILED) {
              s4 = undefined;
            } else {
              peg$currPos = s4;
              s4 = peg$FAILED;
            }
            if (s4 !== peg$FAILED) {
              s5 = peg$currPos;
              peg$begin();
              s6 = peg$parseVoid();
              peg$end(true);
              if (s6 === peg$FAILED) {
                s5 = undefined;
              } else {
                peg$currPos = s5;
                s5 = peg$FAILED;
              }
              if (s5 !== peg$FAILED) {
                s6 = peg$currPos;
                peg$begin();
                s7 = peg$parseComment();
                peg$end(true);
                if (s7 === peg$FAILED) {
                  s6 = undefined;
                } else {
                  peg$currPos = s6;
                  s6 = peg$FAILED;
                }
                if (s6 !== peg$FAILED) {
                  s7 = peg$currPos;
                  peg$begin();
                  s8 = peg$parseDocType();
                  peg$end(true);
                  if (s8 === peg$FAILED) {
                    s7 = undefined;
                  } else {
                    peg$currPos = s7;
                    s7 = peg$FAILED;
                  }
                  if (s7 !== peg$FAILED) {
                    if (input.length > peg$currPos) {
                      s8 = input.charAt(peg$currPos);
                      peg$currPos++;
                    } else {
                      s8 = peg$FAILED;
                    }
                    if (s8 !== peg$FAILED) {
                      peg$savedPos = s2;
                      s2 = peg$f17(s8);
                    } else {
                      peg$currPos = s2;
                      s2 = peg$FAILED;
                    }
                  } else {
                    peg$currPos = s2;
                    s2 = peg$FAILED;
                  }
                } else {
                  peg$currPos = s2;
                  s2 = peg$FAILED;
                }
              } else {
                peg$currPos = s2;
                s2 = peg$FAILED;
              }
            } else {
              peg$currPos = s2;
              s2 = peg$FAILED;
            }
          } else {
            peg$currPos = s2;
            s2 = peg$FAILED;
          }
        }
      } else {
        s1 = peg$FAILED;
      }
      if (s1 !== peg$FAILED) {
        peg$savedPos = s0;
        s1 = peg$f18(s1);
      }
      s0 = s1;
    }
    peg$silentFails--;

    peg$resultsCache[key] = {
      nextPos: peg$currPos,
      result: s0,
      expectations: rule$expectations
    };

    return s0;
  }

  function peg$parsePlaceHolderStart() {
    var s0, s1, s2, s3;

    var rule$expects = function (expected) {
      if (peg$silentFails === 0) peg$expect(expected);
    }

    var key = peg$currPos * 26 + 17;
    var cached = peg$resultsCache[key];
    var rule$expectations = [];

    rule$expects = function (expected) {
      if (peg$silentFails === 0) peg$expect(expected);
      rule$expectations.push(expected);
    }

    if (cached) {
      peg$currPos = cached.nextPos;

      rule$expectations = cached.expectations;
      if (peg$silentFails === 0) {
        rule$expectations.forEach(peg$expect);
      }

      return cached.result;
    }

    s0 = peg$currPos;
    s1 = peg$currPos;
    peg$begin();
    if (peg$r1.test(input.charAt(peg$currPos))) {
      s2 = input.charAt(peg$currPos);
      peg$currPos++;
    } else {
      s2 = peg$FAILED;
    }
    peg$end(true);
    if (s2 === peg$FAILED) {
      s1 = undefined;
    } else {
      peg$currPos = s1;
      s1 = peg$FAILED;
    }
    if (s1 !== peg$FAILED) {
      if (peg$r2.test(input.charAt(peg$currPos))) {
        s2 = input.charAt(peg$currPos);
        peg$currPos++;
      } else {
        s2 = peg$FAILED;
      }
      if (s2 !== peg$FAILED) {
        if (input.charCodeAt(peg$currPos) === 123) {
          s3 = peg$c20;
          peg$currPos++;
        } else {
          s3 = peg$FAILED;
        }
        if (s3 !== peg$FAILED) {
          peg$savedPos = s0;
          s0 = peg$f19(s2);
        } else {
          peg$currPos = s0;
          s0 = peg$FAILED;
        }
      } else {
        peg$currPos = s0;
        s0 = peg$FAILED;
      }
    } else {
      peg$currPos = s0;
      s0 = peg$FAILED;
    }

    peg$resultsCache[key] = {
      nextPos: peg$currPos,
      result: s0,
      expectations: rule$expectations
    };

    return s0;
  }

  function peg$parsePlaceHolderEnd() {
    var s0, s1, s2;

    var rule$expects = function (expected) {
      if (peg$silentFails === 0) peg$expect(expected);
    }

    var key = peg$currPos * 26 + 18;
    var cached = peg$resultsCache[key];
    var rule$expectations = [];

    rule$expects = function (expected) {
      if (peg$silentFails === 0) peg$expect(expected);
      rule$expectations.push(expected);
    }

    if (cached) {
      peg$currPos = cached.nextPos;

      rule$expectations = cached.expectations;
      if (peg$silentFails === 0) {
        rule$expectations.forEach(peg$expect);
      }

      return cached.result;
    }

    s0 = peg$currPos;
    s1 = peg$currPos;
    peg$begin();
    if (peg$r1.test(input.charAt(peg$currPos))) {
      s2 = input.charAt(peg$currPos);
      peg$currPos++;
    } else {
      s2 = peg$FAILED;
    }
    peg$end(true);
    if (s2 === peg$FAILED) {
      s1 = undefined;
    } else {
      peg$currPos = s1;
      s1 = peg$FAILED;
    }
    if (s1 !== peg$FAILED) {
      if (input.charCodeAt(peg$currPos) === 125) {
        s2 = peg$c21;
        peg$currPos++;
      } else {
        s2 = peg$FAILED;
      }
      if (s2 !== peg$FAILED) {
        s1 = [s1, s2];
        s0 = s1;
      } else {
        peg$currPos = s0;
        s0 = peg$FAILED;
      }
    } else {
      peg$currPos = s0;
      s0 = peg$FAILED;
    }

    peg$resultsCache[key] = {
      nextPos: peg$currPos,
      result: s0,
      expectations: rule$expectations
    };

    return s0;
  }

  function peg$parsePlaceHolder() {
    var s0, s1, s2, s3, s4, s5, s6;

    var rule$expects = function (expected) {
      if (peg$silentFails === 0) peg$expect(expected);
    }

    var key = peg$currPos * 26 + 19;
    var cached = peg$resultsCache[key];
    var rule$expectations = [];

    rule$expects = function (expected) {
      if (peg$silentFails === 0) peg$expect(expected);
      rule$expectations.push(expected);
    }

    if (cached) {
      peg$currPos = cached.nextPos;

      rule$expectations = cached.expectations;
      if (peg$silentFails === 0) {
        rule$expectations.forEach(peg$expect);
      }

      return cached.result;
    }

    rule$expects(peg$e9);
    peg$silentFails++;
    s0 = peg$currPos;
    s1 = peg$parsePlaceHolderStart();
    if (s1 !== peg$FAILED) {
      s2 = peg$currPos;
      s3 = [];
      s4 = peg$currPos;
      s5 = peg$currPos;
      peg$begin();
      s6 = peg$parsePlaceHolderEnd();
      peg$end(true);
      if (s6 === peg$FAILED) {
        s5 = undefined;
      } else {
        peg$currPos = s5;
        s5 = peg$FAILED;
      }
      if (s5 !== peg$FAILED) {
        if (input.length > peg$currPos) {
          s6 = input.charAt(peg$currPos);
          peg$currPos++;
        } else {
          s6 = peg$FAILED;
        }
        if (s6 !== peg$FAILED) {
          s5 = [s5, s6];
          s4 = s5;
        } else {
          peg$currPos = s4;
          s4 = peg$FAILED;
        }
      } else {
        peg$currPos = s4;
        s4 = peg$FAILED;
      }
      if (s4 !== peg$FAILED) {
        while (s4 !== peg$FAILED) {
          s3.push(s4);
          s4 = peg$currPos;
          s5 = peg$currPos;
          peg$begin();
          s6 = peg$parsePlaceHolderEnd();
          peg$end(true);
          if (s6 === peg$FAILED) {
            s5 = undefined;
          } else {
            peg$currPos = s5;
            s5 = peg$FAILED;
          }
          if (s5 !== peg$FAILED) {
            if (input.length > peg$currPos) {
              s6 = input.charAt(peg$currPos);
              peg$currPos++;
            } else {
              s6 = peg$FAILED;
            }
            if (s6 !== peg$FAILED) {
              s5 = [s5, s6];
              s4 = s5;
            } else {
              peg$currPos = s4;
              s4 = peg$FAILED;
            }
          } else {
            peg$currPos = s4;
            s4 = peg$FAILED;
          }
        }
      } else {
        s3 = peg$FAILED;
      }
      if (s3 !== peg$FAILED) {
        s2 = input.substring(s2, peg$currPos);
      } else {
        s2 = s3;
      }
      if (s2 !== peg$FAILED) {
        s3 = peg$parsePlaceHolderEnd();
        if (s3 !== peg$FAILED) {
          peg$savedPos = s0;
          s0 = peg$f20(s1, s2);
        } else {
          peg$currPos = s0;
          s0 = peg$FAILED;
        }
      } else {
        peg$currPos = s0;
        s0 = peg$FAILED;
      }
    } else {
      peg$currPos = s0;
      s0 = peg$FAILED;
    }
    peg$silentFails--;

    peg$resultsCache[key] = {
      nextPos: peg$currPos,
      result: s0,
      expectations: rule$expectations
    };

    return s0;
  }

  function peg$parseAttributes() {
    var s0, s1, s2, s3;

    var rule$expects = function (expected) {
      if (peg$silentFails === 0) peg$expect(expected);
    }

    var key = peg$currPos * 26 + 20;
    var cached = peg$resultsCache[key];
    var rule$expectations = [];

    rule$expects = function (expected) {
      if (peg$silentFails === 0) peg$expect(expected);
      rule$expectations.push(expected);
    }

    if (cached) {
      peg$currPos = cached.nextPos;

      rule$expectations = cached.expectations;
      if (peg$silentFails === 0) {
        rule$expectations.forEach(peg$expect);
      }

      return cached.result;
    }

    s0 = peg$currPos;
    s1 = peg$parse__();
    s2 = [];
    s3 = peg$parseAttribute();
    while (s3 !== peg$FAILED) {
      s2.push(s3);
      s3 = peg$parseAttribute();
    }
    s3 = peg$parse__();
    peg$savedPos = s0;
    s0 = peg$f21(s2);

    peg$resultsCache[key] = {
      nextPos: peg$currPos,
      result: s0,
      expectations: rule$expectations
    };

    return s0;
  }

  function peg$parseAttribute() {
    var s0, s1, s2, s3, s4, s5, s6, s7, s8;

    var rule$expects = function (expected) {
      if (peg$silentFails === 0) peg$expect(expected);
    }

    var key = peg$currPos * 26 + 21;
    var cached = peg$resultsCache[key];
    var rule$expectations = [];

    rule$expects = function (expected) {
      if (peg$silentFails === 0) peg$expect(expected);
      rule$expectations.push(expected);
    }

    if (cached) {
      peg$currPos = cached.nextPos;

      rule$expectations = cached.expectations;
      if (peg$silentFails === 0) {
        rule$expectations.forEach(peg$expect);
      }

      return cached.result;
    }

    s0 = peg$currPos;
    s1 = peg$parseNameSpace();
    if (s1 === peg$FAILED) {
      s1 = null;
    }
    s2 = peg$parseSymbol();
    if (s2 !== peg$FAILED) {
      s3 = peg$parse__();
      s4 = peg$currPos;
      s5 = peg$parse__();
      if (input.charCodeAt(peg$currPos) === 61) {
        s6 = peg$c22;
        peg$currPos++;
      } else {
        s6 = peg$FAILED;
      }
      if (s6 !== peg$FAILED) {
        s7 = peg$parse__();
        s8 = peg$parsePlaceHolder();
        if (s8 === peg$FAILED) {
          s8 = peg$parseString();
        }
        if (s8 !== peg$FAILED) {
          s4 = s8;
        } else {
          peg$currPos = s4;
          s4 = peg$FAILED;
        }
      } else {
        peg$currPos = s4;
        s4 = peg$FAILED;
      }
      if (s4 === peg$FAILED) {
        s4 = null;
      }
      s5 = peg$parse__();
      peg$savedPos = s0;
      s0 = peg$f22(s1, s2, s4);
    } else {
      peg$currPos = s0;
      s0 = peg$FAILED;
    }
    if (s0 === peg$FAILED) {
      s0 = peg$currPos;
      s1 = peg$parsePlaceHolder();
      if (s1 !== peg$FAILED) {
        s2 = peg$parse__();
        s0 = s1;
      } else {
        peg$currPos = s0;
        s0 = peg$FAILED;
      }
      if (s0 === peg$FAILED) {
        s0 = peg$currPos;
        s1 = peg$currPos;
        peg$begin();
        if (input.substr(peg$currPos, 2) === peg$c14) {
          s2 = peg$c14;
          peg$currPos += 2;
        } else {
          s2 = peg$FAILED;
        }
        peg$end(true);
        if (s2 === peg$FAILED) {
          s1 = undefined;
        } else {
          peg$currPos = s1;
          s1 = peg$FAILED;
        }
        if (s1 !== peg$FAILED) {
          s2 = [];
          if (peg$r3.test(input.charAt(peg$currPos))) {
            s3 = input.charAt(peg$currPos);
            peg$currPos++;
          } else {
            s3 = peg$FAILED;
          }
          if (s3 !== peg$FAILED) {
            while (s3 !== peg$FAILED) {
              s2.push(s3);
              if (peg$r3.test(input.charAt(peg$currPos))) {
                s3 = input.charAt(peg$currPos);
                peg$currPos++;
              } else {
                s3 = peg$FAILED;
              }
            }
          } else {
            s2 = peg$FAILED;
          }
          if (s2 !== peg$FAILED) {
            s3 = peg$parse__();
            peg$savedPos = s0;
            s0 = peg$f23();
          } else {
            peg$currPos = s0;
            s0 = peg$FAILED;
          }
        } else {
          peg$currPos = s0;
          s0 = peg$FAILED;
        }
      }
    }

    peg$resultsCache[key] = {
      nextPos: peg$currPos,
      result: s0,
      expectations: rule$expectations
    };

    return s0;
  }

  function peg$parseString() {
    var s0, s1, s2, s3, s4, s5, s6, s7;

    var rule$expects = function (expected) {
      if (peg$silentFails === 0) peg$expect(expected);
    }

    var key = peg$currPos * 26 + 22;
    var cached = peg$resultsCache[key];
    var rule$expectations = [];

    rule$expects = function (expected) {
      if (peg$silentFails === 0) peg$expect(expected);
      rule$expectations.push(expected);
    }

    if (cached) {
      peg$currPos = cached.nextPos;

      rule$expectations = cached.expectations;
      if (peg$silentFails === 0) {
        rule$expectations.forEach(peg$expect);
      }

      return cached.result;
    }

    s0 = peg$currPos;
    if (input.charCodeAt(peg$currPos) === 34) {
      s1 = peg$c23;
      peg$currPos++;
    } else {
      s1 = peg$FAILED;
    }
    if (s1 !== peg$FAILED) {
      s2 = [];
      s3 = peg$parsePlaceHolder();
      if (s3 === peg$FAILED) {
        s3 = peg$currPos;
        s4 = [];
        s5 = peg$currPos;
        s6 = peg$currPos;
        peg$begin();
        s7 = peg$parsePlaceHolder();
        peg$end(true);
        if (s7 === peg$FAILED) {
          s6 = undefined;
        } else {
          peg$currPos = s6;
          s6 = peg$FAILED;
        }
        if (s6 !== peg$FAILED) {
          if (peg$r4.test(input.charAt(peg$currPos))) {
            s7 = input.charAt(peg$currPos);
            peg$currPos++;
          } else {
            s7 = peg$FAILED;
          }
          if (s7 !== peg$FAILED) {
            s6 = [s6, s7];
            s5 = s6;
          } else {
            peg$currPos = s5;
            s5 = peg$FAILED;
          }
        } else {
          peg$currPos = s5;
          s5 = peg$FAILED;
        }
        if (s5 !== peg$FAILED) {
          while (s5 !== peg$FAILED) {
            s4.push(s5);
            s5 = peg$currPos;
            s6 = peg$currPos;
            peg$begin();
            s7 = peg$parsePlaceHolder();
            peg$end(true);
            if (s7 === peg$FAILED) {
              s6 = undefined;
            } else {
              peg$currPos = s6;
              s6 = peg$FAILED;
            }
            if (s6 !== peg$FAILED) {
              if (peg$r4.test(input.charAt(peg$currPos))) {
                s7 = input.charAt(peg$currPos);
                peg$currPos++;
              } else {
                s7 = peg$FAILED;
              }
              if (s7 !== peg$FAILED) {
                s6 = [s6, s7];
                s5 = s6;
              } else {
                peg$currPos = s5;
                s5 = peg$FAILED;
              }
            } else {
              peg$currPos = s5;
              s5 = peg$FAILED;
            }
          }
        } else {
          s4 = peg$FAILED;
        }
        if (s4 !== peg$FAILED) {
          s3 = input.substring(s3, peg$currPos);
        } else {
          s3 = s4;
        }
      }
      while (s3 !== peg$FAILED) {
        s2.push(s3);
        s3 = peg$parsePlaceHolder();
        if (s3 === peg$FAILED) {
          s3 = peg$currPos;
          s4 = [];
          s5 = peg$currPos;
          s6 = peg$currPos;
          peg$begin();
          s7 = peg$parsePlaceHolder();
          peg$end(true);
          if (s7 === peg$FAILED) {
            s6 = undefined;
          } else {
            peg$currPos = s6;
            s6 = peg$FAILED;
          }
          if (s6 !== peg$FAILED) {
            if (peg$r4.test(input.charAt(peg$currPos))) {
              s7 = input.charAt(peg$currPos);
              peg$currPos++;
            } else {
              s7 = peg$FAILED;
            }
            if (s7 !== peg$FAILED) {
              s6 = [s6, s7];
              s5 = s6;
            } else {
              peg$currPos = s5;
              s5 = peg$FAILED;
            }
          } else {
            peg$currPos = s5;
            s5 = peg$FAILED;
          }
          if (s5 !== peg$FAILED) {
            while (s5 !== peg$FAILED) {
              s4.push(s5);
              s5 = peg$currPos;
              s6 = peg$currPos;
              peg$begin();
              s7 = peg$parsePlaceHolder();
              peg$end(true);
              if (s7 === peg$FAILED) {
                s6 = undefined;
              } else {
                peg$currPos = s6;
                s6 = peg$FAILED;
              }
              if (s6 !== peg$FAILED) {
                if (peg$r4.test(input.charAt(peg$currPos))) {
                  s7 = input.charAt(peg$currPos);
                  peg$currPos++;
                } else {
                  s7 = peg$FAILED;
                }
                if (s7 !== peg$FAILED) {
                  s6 = [s6, s7];
                  s5 = s6;
                } else {
                  peg$currPos = s5;
                  s5 = peg$FAILED;
                }
              } else {
                peg$currPos = s5;
                s5 = peg$FAILED;
              }
            }
          } else {
            s4 = peg$FAILED;
          }
          if (s4 !== peg$FAILED) {
            s3 = input.substring(s3, peg$currPos);
          } else {
            s3 = s4;
          }
        }
      }
      if (input.charCodeAt(peg$currPos) === 34) {
        s3 = peg$c23;
        peg$currPos++;
      } else {
        s3 = peg$FAILED;
      }
      if (s3 !== peg$FAILED) {
        s4 = peg$parse__();
        peg$savedPos = s0;
        s0 = peg$f14(s2);
      } else {
        peg$currPos = s0;
        s0 = peg$FAILED;
      }
    } else {
      peg$currPos = s0;
      s0 = peg$FAILED;
    }
    if (s0 === peg$FAILED) {
      s0 = peg$currPos;
      if (input.charCodeAt(peg$currPos) === 39) {
        s1 = peg$c24;
        peg$currPos++;
      } else {
        s1 = peg$FAILED;
      }
      if (s1 !== peg$FAILED) {
        s2 = [];
        s3 = peg$parsePlaceHolder();
        if (s3 === peg$FAILED) {
          s3 = peg$currPos;
          s4 = [];
          s5 = peg$currPos;
          s6 = peg$currPos;
          peg$begin();
          s7 = peg$parsePlaceHolder();
          peg$end(true);
          if (s7 === peg$FAILED) {
            s6 = undefined;
          } else {
            peg$currPos = s6;
            s6 = peg$FAILED;
          }
          if (s6 !== peg$FAILED) {
            if (peg$r5.test(input.charAt(peg$currPos))) {
              s7 = input.charAt(peg$currPos);
              peg$currPos++;
            } else {
              s7 = peg$FAILED;
            }
            if (s7 !== peg$FAILED) {
              s6 = [s6, s7];
              s5 = s6;
            } else {
              peg$currPos = s5;
              s5 = peg$FAILED;
            }
          } else {
            peg$currPos = s5;
            s5 = peg$FAILED;
          }
          if (s5 !== peg$FAILED) {
            while (s5 !== peg$FAILED) {
              s4.push(s5);
              s5 = peg$currPos;
              s6 = peg$currPos;
              peg$begin();
              s7 = peg$parsePlaceHolder();
              peg$end(true);
              if (s7 === peg$FAILED) {
                s6 = undefined;
              } else {
                peg$currPos = s6;
                s6 = peg$FAILED;
              }
              if (s6 !== peg$FAILED) {
                if (peg$r5.test(input.charAt(peg$currPos))) {
                  s7 = input.charAt(peg$currPos);
                  peg$currPos++;
                } else {
                  s7 = peg$FAILED;
                }
                if (s7 !== peg$FAILED) {
                  s6 = [s6, s7];
                  s5 = s6;
                } else {
                  peg$currPos = s5;
                  s5 = peg$FAILED;
                }
              } else {
                peg$currPos = s5;
                s5 = peg$FAILED;
              }
            }
          } else {
            s4 = peg$FAILED;
          }
          if (s4 !== peg$FAILED) {
            s3 = input.substring(s3, peg$currPos);
          } else {
            s3 = s4;
          }
        }
        while (s3 !== peg$FAILED) {
          s2.push(s3);
          s3 = peg$parsePlaceHolder();
          if (s3 === peg$FAILED) {
            s3 = peg$currPos;
            s4 = [];
            s5 = peg$currPos;
            s6 = peg$currPos;
            peg$begin();
            s7 = peg$parsePlaceHolder();
            peg$end(true);
            if (s7 === peg$FAILED) {
              s6 = undefined;
            } else {
              peg$currPos = s6;
              s6 = peg$FAILED;
            }
            if (s6 !== peg$FAILED) {
              if (peg$r5.test(input.charAt(peg$currPos))) {
                s7 = input.charAt(peg$currPos);
                peg$currPos++;
              } else {
                s7 = peg$FAILED;
              }
              if (s7 !== peg$FAILED) {
                s6 = [s6, s7];
                s5 = s6;
              } else {
                peg$currPos = s5;
                s5 = peg$FAILED;
              }
            } else {
              peg$currPos = s5;
              s5 = peg$FAILED;
            }
            if (s5 !== peg$FAILED) {
              while (s5 !== peg$FAILED) {
                s4.push(s5);
                s5 = peg$currPos;
                s6 = peg$currPos;
                peg$begin();
                s7 = peg$parsePlaceHolder();
                peg$end(true);
                if (s7 === peg$FAILED) {
                  s6 = undefined;
                } else {
                  peg$currPos = s6;
                  s6 = peg$FAILED;
                }
                if (s6 !== peg$FAILED) {
                  if (peg$r5.test(input.charAt(peg$currPos))) {
                    s7 = input.charAt(peg$currPos);
                    peg$currPos++;
                  } else {
                    s7 = peg$FAILED;
                  }
                  if (s7 !== peg$FAILED) {
                    s6 = [s6, s7];
                    s5 = s6;
                  } else {
                    peg$currPos = s5;
                    s5 = peg$FAILED;
                  }
                } else {
                  peg$currPos = s5;
                  s5 = peg$FAILED;
                }
              }
            } else {
              s4 = peg$FAILED;
            }
            if (s4 !== peg$FAILED) {
              s3 = input.substring(s3, peg$currPos);
            } else {
              s3 = s4;
            }
          }
        }
        if (input.charCodeAt(peg$currPos) === 39) {
          s3 = peg$c24;
          peg$currPos++;
        } else {
          s3 = peg$FAILED;
        }
        if (s3 !== peg$FAILED) {
          s4 = peg$parse__();
          peg$savedPos = s0;
          s0 = peg$f14(s2);
        } else {
          peg$currPos = s0;
          s0 = peg$FAILED;
        }
      } else {
        peg$currPos = s0;
        s0 = peg$FAILED;
      }
      if (s0 === peg$FAILED) {
        s0 = peg$currPos;
        s1 = [];
        s2 = peg$parsePlaceHolder();
        if (s2 === peg$FAILED) {
          s2 = peg$currPos;
          s3 = [];
          s4 = peg$currPos;
          s5 = peg$currPos;
          peg$begin();
          s6 = peg$parsePlaceHolder();
          peg$end(true);
          if (s6 === peg$FAILED) {
            s5 = undefined;
          } else {
            peg$currPos = s5;
            s5 = peg$FAILED;
          }
          if (s5 !== peg$FAILED) {
            if (peg$r6.test(input.charAt(peg$currPos))) {
              s6 = input.charAt(peg$currPos);
              peg$currPos++;
            } else {
              s6 = peg$FAILED;
            }
            if (s6 !== peg$FAILED) {
              s5 = [s5, s6];
              s4 = s5;
            } else {
              peg$currPos = s4;
              s4 = peg$FAILED;
            }
          } else {
            peg$currPos = s4;
            s4 = peg$FAILED;
          }
          if (s4 !== peg$FAILED) {
            while (s4 !== peg$FAILED) {
              s3.push(s4);
              s4 = peg$currPos;
              s5 = peg$currPos;
              peg$begin();
              s6 = peg$parsePlaceHolder();
              peg$end(true);
              if (s6 === peg$FAILED) {
                s5 = undefined;
              } else {
                peg$currPos = s5;
                s5 = peg$FAILED;
              }
              if (s5 !== peg$FAILED) {
                if (peg$r6.test(input.charAt(peg$currPos))) {
                  s6 = input.charAt(peg$currPos);
                  peg$currPos++;
                } else {
                  s6 = peg$FAILED;
                }
                if (s6 !== peg$FAILED) {
                  s5 = [s5, s6];
                  s4 = s5;
                } else {
                  peg$currPos = s4;
                  s4 = peg$FAILED;
                }
              } else {
                peg$currPos = s4;
                s4 = peg$FAILED;
              }
            }
          } else {
            s3 = peg$FAILED;
          }
          if (s3 !== peg$FAILED) {
            s2 = input.substring(s2, peg$currPos);
          } else {
            s2 = s3;
          }
        }
        if (s2 !== peg$FAILED) {
          while (s2 !== peg$FAILED) {
            s1.push(s2);
            s2 = peg$parsePlaceHolder();
            if (s2 === peg$FAILED) {
              s2 = peg$currPos;
              s3 = [];
              s4 = peg$currPos;
              s5 = peg$currPos;
              peg$begin();
              s6 = peg$parsePlaceHolder();
              peg$end(true);
              if (s6 === peg$FAILED) {
                s5 = undefined;
              } else {
                peg$currPos = s5;
                s5 = peg$FAILED;
              }
              if (s5 !== peg$FAILED) {
                if (peg$r6.test(input.charAt(peg$currPos))) {
                  s6 = input.charAt(peg$currPos);
                  peg$currPos++;
                } else {
                  s6 = peg$FAILED;
                }
                if (s6 !== peg$FAILED) {
                  s5 = [s5, s6];
                  s4 = s5;
                } else {
                  peg$currPos = s4;
                  s4 = peg$FAILED;
                }
              } else {
                peg$currPos = s4;
                s4 = peg$FAILED;
              }
              if (s4 !== peg$FAILED) {
                while (s4 !== peg$FAILED) {
                  s3.push(s4);
                  s4 = peg$currPos;
                  s5 = peg$currPos;
                  peg$begin();
                  s6 = peg$parsePlaceHolder();
                  peg$end(true);
                  if (s6 === peg$FAILED) {
                    s5 = undefined;
                  } else {
                    peg$currPos = s5;
                    s5 = peg$FAILED;
                  }
                  if (s5 !== peg$FAILED) {
                    if (peg$r6.test(input.charAt(peg$currPos))) {
                      s6 = input.charAt(peg$currPos);
                      peg$currPos++;
                    } else {
                      s6 = peg$FAILED;
                    }
                    if (s6 !== peg$FAILED) {
                      s5 = [s5, s6];
                      s4 = s5;
                    } else {
                      peg$currPos = s4;
                      s4 = peg$FAILED;
                    }
                  } else {
                    peg$currPos = s4;
                    s4 = peg$FAILED;
                  }
                }
              } else {
                s3 = peg$FAILED;
              }
              if (s3 !== peg$FAILED) {
                s2 = input.substring(s2, peg$currPos);
              } else {
                s2 = s3;
              }
            }
          }
        } else {
          s1 = peg$FAILED;
        }
        if (s1 !== peg$FAILED) {
          s2 = peg$parse__();
          peg$savedPos = s0;
          s0 = peg$f14(s1);
        } else {
          peg$currPos = s0;
          s0 = peg$FAILED;
        }
      }
    }

    peg$resultsCache[key] = {
      nextPos: peg$currPos,
      result: s0,
      expectations: rule$expectations
    };

    return s0;
  }

  function peg$parseSymbol() {
    var s0, s1, s2, s3;

    var rule$expects = function (expected) {
      if (peg$silentFails === 0) peg$expect(expected);
    }

    var key = peg$currPos * 26 + 23;
    var cached = peg$resultsCache[key];
    var rule$expectations = [];

    rule$expects = function (expected) {
      if (peg$silentFails === 0) peg$expect(expected);
      rule$expectations.push(expected);
    }

    if (cached) {
      peg$currPos = cached.nextPos;

      rule$expectations = cached.expectations;
      if (peg$silentFails === 0) {
        rule$expectations.forEach(peg$expect);
      }

      return cached.result;
    }

    s0 = peg$currPos;
    if (peg$r7.test(input.charAt(peg$currPos))) {
      s1 = input.charAt(peg$currPos);
      peg$currPos++;
    } else {
      s1 = peg$FAILED;
    }
    if (s1 !== peg$FAILED) {
      s2 = [];
      if (peg$r7.test(input.charAt(peg$currPos))) {
        s3 = input.charAt(peg$currPos);
        peg$currPos++;
      } else {
        s3 = peg$FAILED;
      }
      while (s3 !== peg$FAILED) {
        s2.push(s3);
        if (peg$r7.test(input.charAt(peg$currPos))) {
          s3 = input.charAt(peg$currPos);
          peg$currPos++;
        } else {
          s3 = peg$FAILED;
        }
      }
      peg$savedPos = s0;
      s0 = peg$f24(s1, s2);
    } else {
      peg$currPos = s0;
      s0 = peg$FAILED;
    }

    peg$resultsCache[key] = {
      nextPos: peg$currPos,
      result: s0,
      expectations: rule$expectations
    };

    return s0;
  }

  function peg$parse__() {
    var s0, s1;

    var rule$expects = function (expected) {
      if (peg$silentFails === 0) peg$expect(expected);
    }

    var key = peg$currPos * 26 + 24;
    var cached = peg$resultsCache[key];
    var rule$expectations = [];

    rule$expects = function (expected) {
      if (peg$silentFails === 0) peg$expect(expected);
      rule$expectations.push(expected);
    }

    if (cached) {
      peg$currPos = cached.nextPos;

      rule$expectations = cached.expectations;
      if (peg$silentFails === 0) {
        rule$expectations.forEach(peg$expect);
      }

      return cached.result;
    }

    rule$expects(peg$e10);
    peg$silentFails++;
    s0 = [];
    if (peg$r8.test(input.charAt(peg$currPos))) {
      s1 = input.charAt(peg$currPos);
      peg$currPos++;
    } else {
      s1 = peg$FAILED;
    }
    while (s1 !== peg$FAILED) {
      s0.push(s1);
      if (peg$r8.test(input.charAt(peg$currPos))) {
        s1 = input.charAt(peg$currPos);
        peg$currPos++;
      } else {
        s1 = peg$FAILED;
      }
    }
    peg$silentFails--;

    peg$resultsCache[key] = {
      nextPos: peg$currPos,
      result: s0,
      expectations: rule$expectations
    };

    return s0;
  }

  function peg$parse_() {
    var s0, s1;

    var rule$expects = function (expected) {
      if (peg$silentFails === 0) peg$expect(expected);
    }

    var key = peg$currPos * 26 + 25;
    var cached = peg$resultsCache[key];
    var rule$expectations = [];

    rule$expects = function (expected) {
      if (peg$silentFails === 0) peg$expect(expected);
      rule$expectations.push(expected);
    }

    if (cached) {
      peg$currPos = cached.nextPos;

      rule$expectations = cached.expectations;
      if (peg$silentFails === 0) {
        rule$expectations.forEach(peg$expect);
      }

      return cached.result;
    }

    s0 = [];
    if (peg$r9.test(input.charAt(peg$currPos))) {
      s1 = input.charAt(peg$currPos);
      peg$currPos++;
    } else {
      s1 = peg$FAILED;
    }
    while (s1 !== peg$FAILED) {
      s0.push(s1);
      if (peg$r9.test(input.charAt(peg$currPos))) {
        s1 = input.charAt(peg$currPos);
        peg$currPos++;
      } else {
        s1 = peg$FAILED;
      }
    }

    peg$resultsCache[key] = {
      nextPos: peg$currPos,
      result: s0,
      expectations: rule$expectations
    };

    return s0;
  }


    const nsPrefix = 'sf';

    class Node {
      constructor(name,attributes,content,namespace = null){
        namespace && (this.namespace = namespace);
        name && (this.name = name);
        attributes && (this.attributes = attributes);
        content && (this.content = content);
      }
    }

    class HtmlNode extends Node {
      constructor(name,attributes,content,namespace){
        super(name,attributes,content,namespace);
      }
    }


    function makeNode(name,attributes,content,namespace){
      // attributesの中にifが含まれるか確認する
      if(attributes && attributes.length){
        for(let i = 0,e = attributes.length;i < e;++i){
          const attr = attributes[i];
          if(attr.namespace == 'sf' && attr.name == 'if'){
            attributes = attributes.splice(i,1);
            const elm  = new HtmlNode(attr.name,[{value:attr.value}],new HtmlNode(name,attributes,content,namespace),attr.namespace);
            elm.if = true;
            return elm;
          }
        }
      }
      return new HtmlNode(name,attributes,content,namespace);
    }

    // function makeHtmlNode(name, attrs,null,namespace){
    //   for(const attr of attrs) {
    //     if(attr.namespace == nsPrefix){
    //       switch(attr.name){
    //         case 'if':
              
    //         break;
    //       }
    //     }
    //   }
    // }
   
    function reduceToObj (xs)
    {
      let attr = {};
      for(const x of xs){
        if(x && x.name){
          attr[x.name] = x.text;
        }
      }
      return attr;
    }


  peg$begin();
  peg$result = peg$startRuleFunction();

  if (peg$result !== peg$FAILED && peg$currPos === input.length) {
    return peg$result;
  } else {
    if (peg$result !== peg$FAILED && peg$currPos < input.length) {
      peg$expect(peg$endExpectation());
    }

    throw peg$buildError();
  }
}

export {
  peg$SyntaxError as SyntaxError,
  peg$parse as parse
};

export default {
  SyntaxError: peg$SyntaxError,
  parse: peg$parse
};
